### ISSUE TITLE
new-delete-type-mismatch detected in C++ parser

### ISSUE THREAD

**Issue by reiniert** [GaloisInc/daedalus#101]
Building and running the C++ parser code generated from a DDL file causes the Address Sanitizer to flag a new-delete-type-mismatch.

**Comment by reiniert** [comment]
The error is as follows:
```
 ==107==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x603000000010 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   20 bytes;
  size of the deallocated type: 16 bytes.
    #0 0x7faa4ed1c025 in operator delete(void*, unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x111025)
    #1 0x561edd496d7b in DDL::Array<DDL::UInt<8> >::free() /daedalus/rts-c/ddl/array.h:130
    #2 0x561edd496d7b in parese_Aircraft_Top(DDL::ParserState&, DDL::Array<Aircraft>*, DDL::Input*, DDL::Input) /gen/Aircraft/ddl/main_parser.cpp:804
    #3 0x561edd498767 in parese_Main(DDL::ParserState&, DDL::Array<Aircraft>*, DDL::Input*, DDL::Input) /gen/Aircraft/ddl/main_parser.cpp:847


    #4 0x561edd498767 in parser /gen/Aircraft/ddl/main_parser.cpp:899
    #5 0x561edd473c39 in main /gen/Aircraft/ddl/main.cpp:60
    #6 0x7faa4e6f50b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #7 0x561edd475a59 in _start (/gen/Aircraft/Aircraft-cdrtestz-ddl-64-asan+0x4a59)

0x603000000010 is located 0 bytes inside of 20-byte region [0x603000000010,0x603000000024)
allocated by thread T0 here:
    #0 0x7faa4ed1a947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x561edd49523a in DDL::Array<DDL::UInt<8> >::Content::allocate(unsigned long) /daedalus/rts-c/ddl/array.h:26
    #2 0x561edd49523a in DDL::Array<DDL::UInt<8> >::Array<DDL::UInt<8>, DDL::UInt<8>, DDL::UInt<8>, DDL::UInt<8> >(unsigned long, DDL::UInt<8>, DDL::UInt<8>, DDL::UInt<8>, DDL::UInt<8>) /daedalus/rts-c/ddl/array.h:53
    #3 0x561edd49523a in parese_Aircraft_Top(DDL::ParserState&, DDL::Array<Aircraft>*, DDL::Input*, DDL::Input) /gen/Aircraft/ddl/main_parser.cpp:824

SUMMARY: AddressSanitizer: new-delete-type-mismatch (/lib/x86_64-linux-gnu/libasan.so.5+0x111025) in operator delete(void*, unsigned long)
```

**Comment by reiniert** [comment]
The DDL used to generate this was:

```
--
-- UTILITY PARSERS
def PadTo n = {
    @here = Offset;
    { (here % n == 0) is true; ^ {} } <| @(Many (n - (here % n))  UInt8);
}

-- *** LITTLE ENDIAN ***
def LE16 = { @b1 = UInt8; @b2 = UInt8; ^ b2 # b1 }
def LE32 = { @w1 = LE16;  @w2 = LE16;  ^ w2 # w1 }
def LE64 = { @w1 = LE32;  @w2 = LE32;  ^ w2 # w1 }
def HighBit = (1 : uint 8) << 7

--
-- BASIC TYPES
--

def Boolean = UInt8 > 0

-- Uint8 is natively supported by Daedalus
def Int8 = {
  @dig = UInt8;
  (dig .&. ~HighBit as int) - (dig .&. HighBit as int)
}

def Uint16 = LE16
def Int16 = {
  @dig1 = UInt8;
  @dig0 = UInt8;
  ((dig0 .&. ~HighBit) # dig1 as int) -
  ((dig0 .&. HighBit as uint 16) << 8 as int)
}

def Uint32 = LE32
def Int32 = { 
  @dig3 = UInt8;
  @dig2 = UInt8;
  @dig1 = UInt8;
  @dig0 = UInt8;
  ((dig0 .&. ~HighBit) # dig1 # dig2 # dig3 as int) -
  ((dig0 .&. HighBit as uint 32) << 24 as int)
}

def Uint64 = LE64
def Int64 = { 
  @dig7 = UInt8;
  @dig6 = UInt8;
  @dig5 = UInt8;
  @dig4 = UInt8;
  @dig3 = UInt8;
  @dig2 = UInt8;
  @dig1 = UInt8;
  @dig0 = UInt8;
  ((dig0 .&. ~HighBit) # dig1 # dig2 # dig3 # dig4 #dig5 #dig6 #dig7 as int) -
  ((dig0 .&. HighBit as uint 64) << 56 as int)
}
-- ***************************
-- * Not directly supported 
-- ***************************

-- def Char = UInt8
def Char = {
    $val = UInt8;
    $type = 'C';
}

-- def WChar = LE16
def WChar = {
    $val = Many (2) UInt8;
    $type = 'R';
}


-- def Float = LE32
def Float = {
    $val = Many (4) UInt8;
    $type = 'F';
}

-- def Double = LE64
def Double = {
    $val = Many (8) UInt8;
    $type = 'D';
}

-- def LongDouble = { @w1 = LE64;  @w2 = LE64;  ^ w1 } -- Not fully supported
def LongDouble = { 
    $val = Many (16) UInt8;
    $type = 'Q';
}

def String = {
    @PadTo 4;
    @len = Uint32; -- Note: length includes string terminator byte
    $val = Many (len as uint 64 - 1) UInt8;
    Match1 0x0; -- String terminator
    $type = 'S';
}

def WString = {
    @PadTo 4;
    @len = Uint32; -- Note: length does NOT includes string terminator byte for Wstring
    $val = Many (len as uint 64) Uint16;
    $type = 'W';
}

-- Sequences of generic type. max can be zero for unbounded sequences
def Sequence $typeName max = {
    @PadTo 4;
    @len = Uint32;
    ( (max > 0) && (len > max)) is false;   -- Fail if seq. exceed max size
    $$ = Many (len as uint 64) $typeName;
}


--struct Aircraft {
--  uint32 object_id;
--  uint32 latitude;
--  uint32 longitude;
--  uint32 altitude;
--};
def Aircraft = {
  @PadTo 4;
  object_id = Uint32;
  @PadTo 4;
  latitude = Uint32;
  @PadTo 4;
  longitude = Uint32;
  @PadTo 4;
  altitude = Uint32;
}

-- Instantiable, top-level includes CDR encapsulation signature
def Aircraft_Top = {
    Match [0x0, 0x1, 0x0, 0x0];
    $$ = Many Aircraft;
}
```

and

```
import Aircraft
def Main = Aircraft_Top
```

**Comment by yav** [comment]
Thank you for reporting this!  Would it be possible to share an input file for the parser that leads to the bug?   It would help narrow down where things are going wrong.

**Comment by yav** [comment]
Nevermind, I was able to reproduce this even without any input, will look into it.

**Comment by yav** [comment]
I fixed that and a few other problems (the mismatch was due to how we were allocating arrays).   I am still seeing some memory leaks with AddressAnalyzer, so I am investigating them.

**Comment by yav** [comment]
OK, I think I cleaned up the memory issues.  I tried a few examples, and they were all clean with both AddressSanitizer and valgrind.    Let me know how if this works for you.

**Comment by reiniert** [comment]
Thanks, that has fixed it.
However, I now get a memory leak reported with the same setup:
```
=================================================================
==8==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fb1b7da3b47 in operator new[](unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10fb47)
    #1 0x55f615985041 in DDL::Array<Aircraft>::Content::allocate(unsigned long) /daedalus/rts-c/ddl/array.h:28
    #2 0x55f615985041 in DDL::Array<Aircraft>::Array(DDL::List<Aircraft>) /daedalus/rts-c/ddl/array.h:61
    #3 0x55f615985041 in parese_Aircraft_Top(DDL::ParserState&, DDL::Array<Aircraft>*, DDL::Input*, DDL::Input) /gen/Aircraft/ddl/main_parser.cpp:796

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
```

**Comment by yav** [comment]
I fixed some stuff related to this yesterday too.   Using a3498dd919ca325a2 I am not getting any memory leaks, could you try it---it also fixes a few other issues where we'd sometimes generate code tat simply won't compile?

FYI, now we also generate a `Makefile.debug` file which builds the project with address sanitizer, let me know if you think we should add more options there.

**Comment by reiniert** [comment]
That commit seems to be older than my issue. I did try it and got the original `new-delete-type-mismatch` back.

**Comment by reiniert** [comment]
I also tried the current HEAD (64727e) and that still showed the memory leak.

**Comment by yav** [comment]
Interesting, I just tried the current head (seems to be the same git hash 64727e995), and I can't seem to reproduce the issue.   I am trying this on Linux, and I tried with both `g++ 9.3.0` and `clang 10.0.0`.   I took the following steps:
  1. `cabal build` to build daedalus
  2. `cabal exec daedalus -- --compile-c++ --out-dir=out Aircraft.ddl`
  3. `make -C out -f Makefile.debug`   to build the parser with the sanitizer optoins.  I've just discovered that this Makefile is `g++` specific in that it links with `lib-asan` while apparently for `clang` you have to use `lib-san`?
  4. `./out/parser`   run the parser with no input

Can you spot any differences with what you did, so we can figure out what's happening?

**Comment by yav** [comment]
Yes, the memory management mechanism is not really documented anywhere yet.  We are using an ownership-based reference counting scheme and it was a lot easier to make the `free` (aka "decrement count") and `copy` (aka "increment count") fully explicit rather than using some sort of smart pointer, in part because it is easy to deallocate something before it goes out of scope, which is a fairly common pattern when giving up ownership.
